(function(g){var window=this;var bqa=function(a,b){return g.Vb(a,b)},b5=function(a,b,c){a.l.set(b,c)},c5=function(a){b5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.D)()).toString(36));
return a},d5=function(a,b,c){g.Ka(c)||(c=[String(c)]);
g.Um(a.l,b,c)},cqa=function(a,b){var c=[];
g.Yi(b,function(d){try{var e=g.Zn.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Da(e)?g.Yn(e)&&c.push(d):c.push(d)},a);
return c},dqa=function(a,b){var c=cqa(a,b);
(0,g.z)(c,function(d){g.Zn.prototype.remove.call(this,d)},a)},e5=function(a){if(a.gd){if(a.gd.locationOverrideToken)return{locationOverrideToken:a.gd.locationOverrideToken};
if(null!=a.gd.latitudeE7&&null!=a.gd.longitudeE7)return{latitudeE7:a.gd.latitudeE7,longitudeE7:a.gd.longitudeE7}}return null},eqa=function(a,b){g.ab(a,b)||a.push(b)},f5=function(a){var b=0,c;
for(c in a)b++;return b},g5=function(a,b){var c=b instanceof g.xc?b:g.Dc(b,/^data:image\//i.test(b));
a.src=g.yc(c)},h5=function(){},fqa=function(a){try{return g.w.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},gqa=function(a){if(a.Ec&&"function"==typeof a.Ec)return a.Ec();
if(g.u(a))return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Qb(a)},hqa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||g.u(a))(0,g.z)(a,b,void 0);else{if(a.Pd&&"function"==typeof a.Pd)var c=a.Pd();else if(a.Ec&&"function"==typeof a.Ec)c=void 0;else if(g.La(a)||g.u(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Rb(a);d=gqa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},iqa=function(a,b,c,d){var e=new g.Im(null,void 0);
a&&g.Jm(e,a);b&&g.Km(e,b);c&&g.Lm(e,c);d&&(e.i=d);return e},i5=function(a,b){g.bp[a]=!0;
var c=g.$o();c&&c.publish.apply(c,arguments);g.bp[a]=!1},j5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Fm;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",jqa(this,a.capabilities||""),kqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},jqa=function(a,b){a.capabilities.clear();
(0,g.Vd)(b.split(","),g.Qa(bqa,lqa)).forEach(function(c){a.capabilities.add(c)})},kqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},k5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},l5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},m5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},mqa=function(a){return new k5(a)},n5=function(a){return g.Ka(a)?(0,g.B)(a,mqa):[]},o5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},p5=function(a){return g.Ka(a)?"["+(0,g.B)(a,o5).join(",")+"]":"null"},q5=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},nqa=function(a){return(0,g.B)(a,function(b){return{key:b.id,
name:b.name}})},r5=function(a,b){return g.Ya(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},s5=function(a,b){return g.Ya(a,function(c){return l5(c,b)})},t5=function(a){try{var b=(0,g.As)(),c=(0,g.zs)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},oqa=function(){var a=(0,g.zs)();
a&&dqa(a,a.g.nf(!0))},u5=function(){var a=g.Cs("yt-remote-connected-devices")||[];
g.qb(a);return a},pqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.B)(a,function(d,e){return 0==e?d:d.substring(c.length)})},v5=function(a){g.Bs("yt-remote-connected-devices",a,86400)},x5=function(){if(w5)return w5;
var a=g.Cs("yt-remote-device-id");a||(a=q5(),g.Bs("yt-remote-device-id",a,31536E3));for(var b=u5(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return w5=d},y5=function(){var a=u5(),b=x5();
g.ab(a,b);g.Ds()&&g.sb(a,b);a=pqa(a);if(0==a.length)try{g.yr("remote_sid")}catch(c){}else try{g.xr("remote_sid",a.join(","),-1)}catch(c){}},z5=function(){return g.Cs("yt-remote-session-browser-channel")},A5=function(){return g.Cs("yt-remote-local-screens")||[]},B5=function(){g.Bs("yt-remote-lounge-token-expiration",!0,86400)},qqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.B)(A5(),function(d){return d.loungeToken}),c=(0,g.B)(a,function(d){return d.loungeToken});
(0,g.eh)(c,function(d){return!g.ab(b,d)})&&B5();
g.Bs("yt-remote-local-screens",a,31536E3)},rqa=function(a,b){g.Bs("yt-remote-session-browser-channel",a);
g.Bs("yt-remote-session-screen-id",b);var c=u5(),d=x5();g.ab(c,d)||c.push(d);v5(c);y5()},C5=function(a){a||(t5("yt-remote-session-screen-id"),t5("yt-remote-session-video-id"));
y5();a=u5();g.db(a,x5());v5(a)},E5=function(){if(!D5){var a=g.jo();
a&&(D5=new g.Tn(a))}return D5?!!D5.get("yt-remote-use-staging-server"):!1},F5=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},G5=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},I5=function(a){a.length?H5(a.shift(),function(){I5(a)}):J5()},sqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},H5=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},J5=function(){var a=G5();
a&&a(!1,"No cast extension found")},K5=function(){if(tqa){var a=2,b=G5(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;H5("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",J5,c)}},uqa=function(){K5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);I5(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},L5=function(a,b,c){g.H.call(this);
this.B=null!=c?(0,g.y)(a,c):a;this.Xc=b;this.A=(0,g.y)(this.oD,this);this.g=!1;this.i=0;this.l=this.Ca=null;this.o=[]},M5=function(a){if(g.w.JSON)try{return g.w.JSON.parse(a)}catch(b){}return fqa(a)},N5=function(){},O5=function(){},P5=function(){},R5=function(a){return(a=Q5(a))?new ActiveXObject(a):new XMLHttpRequest},Q5=function(a){if(!a.i&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.i=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.i},S5=function(a,b,c,d){this.g=a;
this.l=b;this.D=c;this.B=d||1;this.o=45E3;this.ca=new g.aY(this);this.i=new g.al;this.i.setInterval(250)},U5=function(a,b,c){a.Yh=1;
a.Yf=c5(b.clone());a.qh=c;a.A=!0;T5(a,null)},V5=function(a,b,c,d,e){a.Yh=1;
a.Yf=c5(b.clone());a.qh=null;a.A=c;e&&(a.pA=!1);T5(a,d)},T5=function(a,b){a.Di=(0,g.D)();
W5(a);a.Cg=a.Yf.clone();d5(a.Cg,"t",a.B);a.fl=0;a.sc=a.g.Qp(a.g.Qk()?b:null);0<a.zq&&(a.Wn=new g.dl((0,g.y)(a.pB,a,a.sc),a.zq));a.ca.ea(a.sc,"readystatechange",a.gM);var c=a.Yg?g.cc(a.Yg):{};a.qh?(a.Fo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.sc.send(a.Cg,a.Fo,a.qh,c)):(a.Fo="GET",a.pA&&!g.Ld&&(c.Connection="close"),a.sc.send(a.Cg,a.Fo,null,c));a.g.ze(1)},c6=function(a,b,c){for(var d=!0;!a.Ng&&a.fl<c.length;){var e=vqa(a,c);
if(e==X5){4==b&&(a.pg=4,Y5(15),d=!1);break}else if(e==Z5){a.pg=4;Y5(16);d=!1;break}else $5(a,e)}4==b&&0==c.length&&(a.pg=1,Y5(17),d=!1);a.Ae=a.Ae&&d;d||(a6(a),b6(a))},vqa=function(a,b){var c=a.fl,d=b.indexOf("\n",c);
if(-1==d)return X5;c=Number(b.substring(c,d));if(isNaN(c))return Z5;d+=1;if(d+c>b.length)return X5;var e=b.substr(d,c);a.fl=d+c;return e},f6=function(a,b){a.Di=(0,g.D)();
W5(a);var c=b?window.location.hostname:"";a.Cg=a.Yf.clone();b5(a.Cg,"DOMAIN",c);b5(a.Cg,"t",a.B);try{a.Ee=new ActiveXObject("htmlfile")}catch(n){a6(a);a.pg=7;Y5(22);b6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in d6)k=d6[l];else if(l in e6)k=d6[l]=e6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
d6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Rc(g.rc("b/12014412"),d+"</body></html>");a.Ee.open();a.Ee.write(g.Mc(c));a.Ee.close();a.Ee.parentWindow.m=(0,g.y)(a.wL,a);a.Ee.parentWindow.d=(0,g.y)(a.yz,a,!0);a.Ee.parentWindow.rpcClose=(0,g.y)(a.yz,a,!1);c=a.Ee.createElement("DIV");a.Ee.parentWindow.document.body.appendChild(c);d=g.Cc(a.Cg.toString());d=g.Yc(g.zc(d));d=g.Rc(g.rc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Sc(c,d);a.g.ze(1)},W5=function(a){a.Bt=(0,g.D)()+a.o;
g6(a,a.o)},g6=function(a,b){if(null!=a.Ti)throw Error("WatchDog timer not null");
a.Ti=h6((0,g.y)(a.GL,a),b)},i6=function(a){a.Ti&&(g.w.clearTimeout(a.Ti),a.Ti=null)},b6=function(a){a.g.ww()||a.Ng||a.g.Kn(a)},a6=function(a){i6(a);
g.Bi(a.Wn);a.Wn=null;a.i.stop();g.cY(a.ca);if(a.sc){var b=a.sc;a.sc=null;b.abort();b.dispose()}a.Ee&&(a.Ee=null)},$5=function(a,b){try{a.g.rz(a,b),a.g.ze(4)}catch(c){}},k6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;j6(a,b,function(k){k?c(!0):g.w.setTimeout(function(){k6(a,b,c,d,f)},f)})}},j6=function(a,b,c){var d=new Image;
d.onload=function(){try{l6(d),c(!0)}catch(e){}};
d.onerror=function(){try{l6(d),c(!1)}catch(e){}};
d.onabort=function(){try{l6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{l6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
g5(d,a)},l6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},m6=function(a){this.g=a;
this.i=new N5},o6=function(a){var b=n6(a.g,a.hj,"/mail/images/cleardot.gif");
c5(b);k6(b.toString(),5E3,(0,g.y)(a.vC,a),3,2E3);a.ze(1)},q6=function(a){var b=a.g.G;
if(null!=b)Y5(5),b?(Y5(11),p6(a.g,a,!1)):(Y5(12),p6(a.g,a,!0));else if(a.Gd=new S5(a,void 0,void 0,void 0),a.Gd.Yg=a.xq,b=a.g,b=n6(b,b.Qk()?a.Mj:null,a.yq),Y5(5),!g.Jd||g.ld(10))d5(b,"TYPE","xmlhttp"),V5(a.Gd,b,!1,a.Mj,!1);else{d5(b,"TYPE","html");var c=a.Gd;a=!!a.Mj;c.Yh=3;c.Yf=c5(b.clone());f6(c,a)}},r6=function(a){g.qk.call(this);
this.headers=new g.Fm;this.N=a||null;this.i=!1;this.T=this.g=null;this.Z=this.F="";this.A=0;this.l="";this.o=this.aa=this.D=this.R=!1;this.B=0;this.G=null;this.X="";this.J=this.S=!1},wqa=function(a){return g.Jd&&g.kd(9)&&g.Fa(a.timeout)&&g.Da(a.ontimeout)},xqa=function(a){return"content-type"==a.toLowerCase()},u6=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.A=5;s6(a);t6(a)},s6=function(a){a.R||(a.R=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},x6=function(a){if(a.i&&"undefined"!=typeof g.gY)if(a.T[1]&&4==v6(a)&&2==a.getStatus())w6(a,"Local request error detected and ignored");
else if(a.D&&4==v6(a))g.bl(a.yw,0,a);else if(a.dispatchEvent("readystatechange"),4==v6(a)){w6(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.tf(1,String(a.F));if(!f&&g.w.self&&g.w.self.location){var k=g.w.self.location.protocol;f=k.substr(0,k.length-1)}e=!yqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.A=6;try{var l=2<v6(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";s6(a)}}finally{t6(a)}}},t6=function(a,b){if(a.g){y6(a);
var c=a.g,d=a.T[0]?g.Ha:null;a.g=null;a.T=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},y6=function(a){a.g&&a.J&&(a.g.ontimeout=null);
a.G&&(g.w.clearTimeout(a.G),a.G=null)},v6=function(a){return a.g?a.g.readyState:0},z6=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},w6=function(a,b){return b+" ["+a.Z+" "+a.F+" "+a.getStatus()+"]"},A6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.A=new N5;this.F=a||null;this.G=null!=b?b:null;this.B=c||!1},zqa=function(a,b){this.g=a;
this.map=b;this.context=null},B6=function(a){g.Sj.call(this,"statevent",a)},C6=function(a,b){g.Sj.call(this,"timingevent",a);
this.size=b},D6=function(a){g.Sj.call(this,"serverreachability",a)},H6=function(a){E6(a);
if(3==a.g){var b=a.vk++,c=a.im.clone();b5(c,"SID",a.l);b5(c,"RID",b);b5(c,"TYPE","terminate");F6(a,c);b=new S5(a,a.l,b,void 0);b.Yh=2;b.Yf=c5(c.clone());g5(new Image,b.Yf.toString());b.Di=(0,g.D)();W5(b)}G6(a)},J6=function(a){a.NC(1,0);
a.im=n6(a,null,a.wq);I6(a)},E6=function(a){a.fg&&(a.fg.abort(),a.fg=null);
a.Rb&&(a.Rb.cancel(),a.Rb=null);a.qf&&(g.w.clearTimeout(a.qf),a.qf=null);K6(a);a.Cd&&(a.Cd.cancel(),a.Cd=null);a.ng&&(g.w.clearTimeout(a.ng),a.ng=null)},L6=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new zqa(a.KH++,b));2!=a.g&&3!=a.g||I6(a)},I6=function(a){a.Cd||a.ng||(a.ng=h6((0,g.y)(a.xz,a),0),a.Rh=0)},O6=function(a,b){if(1==a.g){if(!b){a.vk=Math.floor(1E5*Math.random());
var c=a.vk++,d=new S5(a,"",c,void 0);d.Yg=null;var e=M6(a),f=a.im.clone();b5(f,"RID",c);b5(f,"CVER","1");F6(a,f);U5(d,f,e);a.Cd=d;a.g=2}}else 3==a.g&&(b?N6(a,b):0==a.i.length||a.Cd||N6(a))},N6=function(a,b){if(b)if(6<a.Og){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.vk-1;var d=M6(a)}else c=b.D,d=b.qh;else c=a.vk++,d=M6(a);var e=a.im.clone();b5(e,"SID",a.l);b5(e,"RID",c);b5(e,"AID",a.li);F6(a,e);c=new S5(a,a.l,c,a.Rh+1);c.Yg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Cd=c;U5(c,e,d)},F6=function(a,b){if(a.Uc){var c=a.Uc.Uv();
c&&g.Kb(c,function(d,e){b5(b,e,d)})}},M6=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Og&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Og?e:f-d;try{g.Kb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},P6=function(a){a.Rb||a.qf||(a.D=1,a.qf=h6((0,g.y)(a.wz,a),0),a.Kh=0)},R6=function(a){if(a.Rb||a.qf||3<=a.Kh)return!1;
a.D++;a.qf=h6((0,g.y)(a.wz,a),Q6(a,a.Kh));a.Kh++;return!0},p6=function(a,b,c){a.Do=c;
a.Je=b.Cf;a.B||J6(a)},K6=function(a){null!=a.Sg&&(g.w.clearTimeout(a.Sg),a.Sg=null)},Q6=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},T6=function(a,b){if(2==b||9==b){var c=null;
a.Uc&&(c=null);var d=(0,g.y)(a.JM,a);c||(c=new g.Im("//www.google.com/images/cleardot.gif"),c5(c));j6(c.toString(),1E4,d)}else Y5(2);S6(a,b)},S6=function(a,b){a.g=0;
a.Uc&&a.Uc.Tu(b);G6(a);E6(a)},G6=function(a){a.g=0;
a.Je=-1;if(a.Uc)if(0==a.o.length&&0==a.i.length)a.Uc.Dp();else{g.gb(a.o);var b=g.gb(a.i);a.o.length=0;a.i.length=0;a.Uc.Dp(b)}},n6=function(a,b,c){var d=g.Qm(c);
if(""!=d.g)b&&g.Km(d,b+"."+d.g),g.Lm(d,d.A);else{var e=window.location;d=iqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.vj&&g.Kb(a.vj,function(f,k){b5(d,k,f)});
b5(d,"VER",a.Og);F6(a,d);return d},h6=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},Y5=function(a){U6.dispatchEvent(new B6(U6,a))},V6=function(){},W6=function(){this.g=[];
this.i=[]},Aqa=function(a,b){this.action=a;
this.params=b||{}},X6=function(a,b){g.H.call(this);
this.g=new g.K(this.oL,0,this);g.J(this,this.g);this.Xc=5E3;this.i=0;if(g.Ma(a))b&&(a=(0,g.y)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.y)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},Y6=function(a,b,c){this.I=a;
this.B=b;this.l=new g.Sn;this.i=new X6(this.qM,this);this.g=null;this.ib=!1;this.A=null;this.G="";this.F=this.o=0;this.D=[];this.J=c||!1},Bqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Do,sessionId:a.g.l,arrayId:a.g.li}},Z6=function(a,b){a.F=b||0;
a.i.stop();a.g&&(3==a.g.g&&O6(a.g),H6(a.g));a.F=0},$6=function(a){return!!a.g&&3==a.g.g},Cqa=function(a,b){(a.B.loungeIdToken=b)||a.i.stop()},a7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.tf(4,a))||"";b&&(this.port=":"+b);this.domain=g.uf(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.i=!1))},b7=function(a,b){var c=a.g;
if(g.Da(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.Ef(c+b,{})},c7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.o,d,!0),onError:g.Qa(a.l,e),oe:g.Qa(a.A,e)};c&&(a.ub=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Up(b,a)},Dqa=function(){var a=d7;
e7();f7.push(a);g7(f7)},h7=function(a,b){e7();
var c=f7,d=Eqa(a,String(b));0==c.length?Fqa(d):(g7(c),(0,g.z)(c,function(e){e(d)}))},e7=function(){f7||(f7=g.x("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",f7,void 0))},Fqa=function(a){var b=(i7+1)%50;
i7=b;j7[b]=a;k7||(k7=49==b)},g7=function(a){var b=j7;
if(b[0]){var c=i7,d=k7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.z)(a,function(f){f(e)})}while(d!=c);
j7=Array(50);i7=-1;k7=!1}},Eqa=function(a,b){var c=((0,g.D)()-Gqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},l7=function(a){g.O.call(this);
this.D=a;this.g=[]},m7=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Hqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Vd)(a.g,function(f){return!!r5(b,f)});
for(var d=0,e=b.length;d<e;d++)c=m7(a,b[d])||c;return c},Iqa=function(a,b){var c=a.g.length;
a.g=(0,g.Vd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},n7=function(a,b,c,d){g.O.call(this);
this.B=a;this.A=b;this.l=c;this.o=d;this.i=0;this.g=null;this.Ca=NaN},p7=function(a){l7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;o7(this);this.info("Initializing with "+p5(this.g))},q7=function(a){if(a.g.length){var b=(0,g.B)(a.g,function(d){return d.id}),c=b7(a.l,"/pairing/get_lounge_token_batch");
c7(a.l,c,{screen_ids:b.join(",")},(0,g.y)(a.yD,a),(0,g.y)(a.xD,a))}},o7=function(a){var b=n5(A5());
b=(0,g.Vd)(b,function(c){return!c.uuid});
return Hqa(a,b)},r7=function(a,b){qqa((0,g.B)(a.g,m5));
b&&B5()},t7=function(a,b){g.O.call(this);
this.B=b;var c=g.Cs("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.B(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.g=d;this.A=a;this.l=this.o=NaN;this.i=null;s7("Initialized with "+g.rm(this.g))},u7=function(a,b,c){var d=b7(a.A,"/pairing/get_screen_availability");
c7(a.A,d,{lounge_token:b.token},(0,g.y)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.y)(function(){c(!1)},a))},v7=function(a,b){a:if(f5(b)!=f5(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(s7("Updated online screens: "+g.rm(a.g)),a.g=b,a.O("screenChange"));Jqa(a)},w7=function(a){isNaN(a.l)||g.Zo(a.l);
a.l=g.Xo((0,g.y)(a.Fs,a),0<a.o&&a.o<(0,g.D)()?2E4:1E4)},s7=function(a){h7("OnlineScreenService",a)},x7=function(a){var b={};
(0,g.z)(a.B(),function(c){c.token?b[c.token]=c.id:this.Ib("Requesting availability of screen w/o lounge token.")});
return b},Jqa=function(a){a=g.Rb(g.Lb(a.g,function(b){return b}));
g.qb(a);a.length?g.Bs("yt-remote-online-screen-ids",a.join(","),60):t5("yt-remote-online-screen-ids")},y7=function(a){l7.call(this,"ScreenService");
this.B=a;this.i=this.l=null;this.o=[];this.A={};Kqa(this)},A7=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.A[b]);var k=a.Qd();if(k=(c?s5(k,c):null)||s5(k,b)){k.uuid=b;var l=z7(a,k);u7(a.i,l,function(m){e(m?l:null)})}else c?Lqa(a,c,(0,g.y)(function(m){var n=z7(this,new k5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));u7(this.i,n,function(q){e(q?n:null)})},a),f):e(null)},B7=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Lqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={ub:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Up(b7(a.B,"/pairing/get_lounge_token_batch"),e)},C7=function(a){a.g=a.l.Qd();
var b=a.A,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+p5(a.g))},Kqa=function(a){D7(a);
a.l=new p7(a.B);a.l.subscribe("screenChange",(0,g.y)(a.GD,a));C7(a);a.o=n5(g.Cs("yt-remote-automatic-screen-cache")||[]);D7(a);a.info("Initializing automatic screens: "+p5(a.o));a.i=new t7(a.B,(0,g.y)(a.Qd,a,!0));a.i.subscribe("screenChange",(0,g.y)(function(){this.O("onlineScreenChange")},a))},z7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=s5(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.Bs("yt-remote-automatic-screen-cache",(0,g.B)(a.o,m5)));D7(a);a.A[b.uuid]=b.id;g.Bs("yt-remote-device-id-map",a.A,31536E3);return b},D7=function(a){a.A=g.Cs("yt-remote-device-id-map")||{}},E7=function(a,b,c){g.O.call(this);
this.T=c;this.G=a;this.i=b;this.l=null},F7=function(a,b){h7(a.T,b)},H7=function(a,b){E7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.B=(0,g.y)(this.qN,this);this.A=(0,g.y)(this.RL,this);this.o=g.Xo((0,g.y)(function(){G7(this,null)},this),12E4)},Mqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.rm(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ha,(0,g.y)(function(){F7(this,"Failed to send message: getMdxSessionStatus.")},a)):F7(a,"Sending yt message without session: "+g.rm(b))},G7=function(a,b){g.Zo(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.y)(a.Mn,a),d=(0,g.y)(a.Td,a);a.mw(b,c,d,5)}}else a.Td(Error("Waiting for session status timed out."))},I7=function(a,b,c){E7.call(this,a,b,"DialSession");
this.o=this.F=null;this.I="";this.N=c;this.A=null;this.D=g.Ha;this.B=NaN;this.J=(0,g.y)(this.tN,this);this.g=g.Ha},J7=function(a){a.g=a.G.uB(a.I,a.i.label,a.i.friendlyName,(0,g.y)(function(b){this.g=g.Ha;
this.Mn(b)},a),(0,g.y)(function(b){this.g=g.Ha;
this.Td(b)},a))},K7=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.A){var c=a.A.currentTime||0;b.v=a.A.videoId;b.t=c}E5()&&(b.env_useStageMdx=1);return g.Cf(b)},L7=function(a,b){E7.call(this,a,b,"ManualSession");
this.g=g.Xo((0,g.y)(this.mi,this,null),150)},M7=function(a,b,c,d){g.O.call(this);
this.i=a;this.D=b||"233637DE";this.B=c||"cl";this.F=d||!1;this.g=null;this.A=!1;this.l=[];this.o=(0,g.y)(this.wK,this)},N7=function(a,b){return b?g.Ya(a.l,function(c){return l5(b,c.label)},a):null},O7=function(a){h7("Controller",a)},d7=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},P7=function(a){return a.A||!!a.l.length||!!a.g},Q7=function(a,b,c){b!=a.g&&(g.Bi(a.g),(a.g=b)?(c?a.O("yt-remote-cast2-receiver-resumed",b.i):a.O("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.y)(a.vz,a,b)),b.l?a.O("yt-remote-cast2-session-change",b.l):c&&a.g.mi(null)):a.O("yt-remote-cast2-session-change",null))},R7=function(a){var b=a.i.tB(),c=a.g&&a.g.i;
a=(0,g.B)(b,function(d){c&&l5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=N7(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Qqa=function(a,b,c,d,e,f,k){Nqa()?Oqa(b,e,f,k)&&(T7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?U7(a,c):(window.__onGCastApiAvailable=function(l,m){l?U7(a,c):(V7("Failed to load cast API: "+m),W7(!1),T7(!1),t5("yt-remote-cast-available"),t5("yt-remote-cast-receiver"),X7(),c(!1))},d?g.jp("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?uqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?J5():(K5(),I5(Pqa.map(sqa))))):S7("Cannot initialize because not running Chrome")},X7=function(){S7("dispose");
var a=Y7();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);Z7(!1);g.ep($7);$7.length=0},a8=function(){return!!g.Cs("yt-remote-cast-installed")},b8=function(){var a=g.Cs("yt-remote-cast-receiver");
return a?a.friendlyName:null},c8=function(){S7("clearCurrentReceiver");
t5("yt-remote-cast-receiver")},d8=function(){return a8()?Y7()?Y7().getCastSession():(V7("getCastSelector: Cast is not initialized."),null):(V7("getCastSelector: Cast API is not installed!"),null)},f8=function(){a8()?Y7()?e8()?(S7("Requesting cast selector."),Y7().requestSession()):(S7("Wait for cast API to be ready to request the session."),$7.push(g.dp("yt-remote-cast2-api-ready",f8))):V7("requestCastSelector: Cast is not initialized."):V7("requestCastSelector: Cast API is not installed!")},g8=function(a,
b){e8()?Y7().setConnectedScreenStatus(a,b):V7("setConnectedScreenStatus called before ready.")},Nqa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.ow||a},Rqa=function(a,b){Y7().init(a,b)},Oqa=function(a,b,c,d){var e=!1;
Y7()||(a=new M7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Bs("yt-remote-cast-available",f);i5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){S7("onReceiverSelected: "+f.friendlyName);
g.Bs("yt-remote-cast-receiver",f);i5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){S7("onReceiverResumed: "+f.friendlyName);
g.Bs("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){S7("onSessionChange: "+o5(f));
f||t5("yt-remote-cast-receiver");i5("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
S7("cloudview.createSingleton_: "+e);return e},Y7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},U7=function(a,b){W7(!0);
T7(!1);Rqa(a,function(c){c?(Z7(!0),g.gp("yt-remote-cast2-api-ready")):(V7("Failed to initialize cast API."),W7(!1),t5("yt-remote-cast-available"),t5("yt-remote-cast-receiver"),X7());b(c)})},S7=function(a){h7("cloudview",a)},V7=function(a){h7("cloudview",a)},W7=function(a){S7("setCastInstalled_ "+a);
g.Bs("yt-remote-cast-installed",a)},e8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},Z7=function(a){S7("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},T7=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},h8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.B=this.D=0;this.g=null;this.hasNext=this.Ke=!1;this.G=this.F=this.i=this.o=0;this.l=NaN;this.A=!1;this.reset(a)},i8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Ke=!1;a.hasNext=!1;a.D=0;a.B=(0,g.D)();a.o=0;a.i=0;a.F=0;a.G=0;a.l=NaN;a.A=!1},j8=function(a){return 1==a.playerState?((0,g.D)()-a.B)/1E3:0},k8=function(a,b){a.D=b;
a.B=(0,g.D)()},l8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.B)/1E3+a.D;
case -1E3:return 0}return a.D},m8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&i8(a)},n8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.g);b.hasPrevious=a.Ke;b.hasNext=a.hasNext;b.playerTime=a.D;b.playerTimeAt=a.B;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.F;b.loadedTime=a.G;b.liveIngestionTime=a.l;return b},q8=function(a,b){g.O.call(this);
this.g=0;this.o=a;this.B=[];this.A=new W6;this.l=this.i=null;this.G=(0,g.y)(this.sI,this);this.D=(0,g.y)(this.yk,this);this.F=(0,g.y)(this.rI,this);this.I=(0,g.y)(this.GI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Et,this),o8(this))):c=3;0!=c&&(b?this.Et(c):g.Xo((0,g.y)(function(){this.Et(c)},this),0));
var d=d8();d&&p8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},r8=function(a){return new h8(a.o.getPlayerContextData())},o8=function(a){(0,g.z)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.B.push(this.o.subscribe(b,g.Qa(this.tK,b),this))},a)},s8=function(a){(0,g.z)(a.B,function(b){this.o.unsubscribeByKey(b)},a);
a.B.length=0},t8=function(a,b){var c=a.A;
50>c.g.length+c.i.length&&a.A.i.push(b)},v8=function(a,b,c){var d=r8(a);
k8(d,c);-1E3!=d.playerState&&(d.playerState=b);u8(a,d)},w8=function(a,b,c){a.o.sendMessage(b,c)},u8=function(a,b){s8(a);
a.o.setPlayerContextData(n8(b));o8(a)},p8=function(a,b){a.l&&(a.l.removeUpdateListener(a.G),a.l.removeMediaListener(a.D),a.yk(null));
a.l=b;a.l&&(h7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.G),a.l.addMediaListener(a.D),a.l.media.length&&a.yk(a.l.media[0]))},x8=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=r8(a);b.contentId!=d.videoId&&h7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;k8(d,a.i.getEstimatedTime());u8(a,d)}else h7("CP","No cast media video. Ignoring state update.")},y8=function(a,b,c){return(0,g.y)(function(d){this.Ib("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Ib("Retrying "+b+" using MDx browser channel."),w8(this,b,c))},a)},z8=function(a,b,c){g.O.call(this);
this.A=NaN;this.J=!1;this.F=this.D=this.G=this.I=NaN;this.T=[];this.o=this.B=this.l=this.Oa=this.g=null;this.R=a;this.T.push(g.cr(window,"beforeunload",(0,g.y)(this.rD,this)));this.i=[];this.Oa=new h8;this.N=b.id;this.g=Sqa(this,c);this.g.subscribe("handlerOpened",this.wI,this);this.g.subscribe("handlerClosed",this.tI,this);this.g.subscribe("handlerError",this.uI,this);this.g.subscribe("handlerMessage",this.vI,this);Cqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Oa.videoId;
g.Ds()&&g.Bs("yt-remote-session-video-id",d)},this)},A8=function(a){h7("conn",a)},Sqa=function(a,b){return new Y6(b7(a.R,"/bc"),b)},B8=function(a,b){a.O("proxyStateChange",b)},Tqa=function(a){a.A=g.Xo((0,g.y)(function(){A8("Connecting timeout");
this.Oh(1)},a),2E4)},C8=function(a){g.Zo(a.A);
a.A=NaN},D8=function(a){g.Zo(a.I);
a.I=NaN},Uqa=function(a){E8(a);
a.G=g.Xo((0,g.y)(function(){F8(this,"getNowPlaying")},a),2E4)},E8=function(a){g.Zo(a.G);
a.G=NaN},H8=function(a,b){b&&(C8(a),D8(a));
b==($6(a.g)&&isNaN(a.A))?b&&(B8(a,1),F8(a,"getSubtitlesTrack")):b?(a.kw()&&a.Oa.reset(),B8(a,1),F8(a,"getNowPlaying"),G8(a)):a.Oh(1)},Vqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Oa.videoId&&(g.Yb(b.params)?a.Oa.g=null:a.Oa.g=b.params,a.O("remotePlayerChange"))},I8=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Oa.listId=b.params.listId||a.Oa.listId;m8(a.Oa,c,d);a.O("remoteQueueChange")},Wqa=function(a,b){b.params=b.params||{};
I8(a,b);J8(a,b);a.O("autoplayDismissed")},J8=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
k8(a.Oa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Oa.playerState&&(c=-1E3);a.Oa.playerState=c;c=Number(b.params.loadedTime);a.Oa.G=isNaN(c)?0:c;c=Number(b.params.duration);a.Oa.F=isNaN(c)?0:c;c=a.Oa;var d=Number(b.params.liveIngestionTime);c.l=d;c.A=isNaN(d)?!1:!0;c=a.Oa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Oa.playerState?Uqa(a):E8(a);a.O("remotePlayerChange")},Xqa=function(a,b){if(-1E3!=
a.Oa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Oa.playerState=c;c=parseInt(b.params.currentTime,10);k8(a.Oa,isNaN(c)?0:c);a.O("remotePlayerChange")}},Yqa=function(a,b){var c="true"==b.params.muted;
a.Oa.volume=parseInt(b.params.volume,10);a.Oa.muted=c;a.O("remotePlayerChange")},Zqa=function(a,b){a.B=b.params.videoId;
a.O("nowAutoplaying",parseInt(b.params.timeout,10))},$qa=function(a,b){var c="true"==b.params.hasNext;
a.Oa.Ke="true"==b.params.hasPrevious;a.Oa.hasNext=c;a.O("previousNextChange")},G8=function(a){g.Zo(a.F);
a.F=g.Xo((0,g.y)(a.Oh,a,1),864E5)},F8=function(a,b,c){c?A8("Sending: action="+b+", params="+g.rm(c)):A8("Sending: action="+b);
a.g.sendMessage(b,c)},K8=function(a){l7.call(this,"ScreenServiceProxy");
this.Wc=a;this.i=[];this.i.push(this.Wc.$_s("screenChange",(0,g.y)(this.oN,this)));this.i.push(this.Wc.$_s("onlineScreenChange",(0,g.y)(this.YJ,this)))},era=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Po("MDX_CONFIG")||b;oqa();y5();L8||(L8=new a7(b?b.loungeApiHost:void 0),E5()&&(L8.g="/api/loungedev"));M8||(M8=g.x("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",M8,void 0));ara();var c=N8();if(!c){var d=new y7(L8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=N8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Qqa(a,d,function(m){m?O8()&&g8(O8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){i5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),P8("Initializing: "+g.rm(b)),Q8.push(g.dp("yt-remote-cast2-availability-change",function(){i5("yt-remote-receiver-availability-change")})),Q8.push(g.dp("yt-remote-cast2-receiver-selected",function(){R8(null);
i5("yt-remote-auto-connect","cast-selector-receiver")})),Q8.push(g.dp("yt-remote-cast2-receiver-resumed",function(){i5("yt-remote-receiver-resumed","cast-selector-receiver")})),Q8.push(g.dp("yt-remote-cast2-session-change",bra)),Q8.push(g.dp("yt-remote-connection-change",function(m){m?g8(O8(),"YouTube TV"):S8()||(g8(null,null),c8())})),a=T8(),b.isAuto&&(a.id+="#dial"),g.Lp("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),P8(" -- with channel params: "+
g.rm(a)),cra(a),c.start(),O8()||dra())},fra=function(){var a=U8();
a8()&&g.Cs("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},U8=function(){var a=N8().Wc.$_gos();
var b=V8();b&&W8()&&(r5(a,b)||a.push(b));return nqa(a)},X8=function(){var a=gra();
!a&&a8()&&b8()&&(a={key:"cast-selector-receiver",name:b8()});return a},gra=function(){var a=U8(),b=V8();
b||(b=S8());return g.Ya(a,function(c){return b&&l5(b,c.key)?!0:!1})},V8=function(){var a=O8();
if(!a)return null;var b=N8().Qd();return s5(b,a)},bra=function(a){P8("remote.onCastSessionChange_: "+o5(a));
if(a){var b=V8();b&&b.id==a.id?g8(b.id,"YouTube TV"):(b&&Y8(),Z8(a,1))}else W8()&&Y8()},Y8=function(){e8()?Y7().stopSession():V7("stopSession called before API ready.");
var a=W8();a&&(a.disconnect(1),$8(null))},a9=function(){var a=W8();
return!!a&&3!=a.getProxyState()},P8=function(a){h7("remote",a)},N8=function(){if(!b9){var a=g.x("yt.mdx.remote.screenService_");
b9=a?new K8(a):null}return b9},O8=function(){return g.x("yt.mdx.remote.currentScreenId_")},c9=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},d9=function(){return g.x("yt.mdx.remote.connectData_")},R8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},W8=function(){return g.x("yt.mdx.remote.connection_")},$8=function(a){var b=W8();
R8(null);a||c9("");g.Ga("yt.mdx.remote.connection_",a,void 0);M8&&((0,g.z)(M8,function(c){c(a)}),M8.length=0);
b&&!a?i5("yt-remote-connection-change",!1):!b&&a&&i5("yt-remote-connection-change",!0)},S8=function(){var a=g.Ds();
if(!a)return null;var b=N8().Qd();return s5(b,a)},Z8=function(a,b){V8()&&V8();
if(e9)f9=a;else{c9(a.id);var c=new z8(L8,a,T8());c.connect(b,d9());c.subscribe("beforeDisconnect",function(d){i5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){W8()&&$8(null)});
$8(c)}},dra=function(){var a=S8();
a?(P8("Resume connection to: "+o5(a)),Z8(a,0)):(C5(),c8(),P8("Skipping connecting because no session screen found."))},ara=function(){var a=T8();
if(g.Yb(a)){a=x5();var b=g.Cs("yt-remote-session-name")||"",c=g.Cs("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},T8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},cra=function(a){a?(g.Bs("yt-remote-session-app",a.app),g.Bs("yt-remote-session-name",a.name)):(t5("yt-remote-session-app"),t5("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},g9=function(a,b,c){g.H.call(this);
this.A=a;this.i=b;this.l=new g.Or(this);g.J(this,this.l);this.l.L(b,"onCaptionsTrackListChanged",this.tJ);this.l.L(b,"captionschanged",this.qI);this.l.L(b,"captionssettingschanged",this.HA);this.l.L(b,"videoplayerreset",this.Nn);this.l.L(b,"mdxautoplaycancel",this.uC);this.R=this.l.L(b,"onVolumeChange",this.ez);this.F=!1;this.g=c;c.subscribe("proxyStateChange",this.qz,this);c.subscribe("remotePlayerChange",this.Ak,this);c.subscribe("remoteQueueChange",this.Nn,this);c.subscribe("autoplayUpNext",this.Ty,
this);c.subscribe("previousNextChange",this.nz,this);c.subscribe("nowAutoplaying",this.jz,this);c.subscribe("autoplayDismissed",this.Sy,this);this.suggestion=null;this.G=new g.NB(64);this.o=new g.K(this.FA,500,this);g.J(this,this.o);this.B=new g.K(this.GA,1E3,this);g.J(this,this.B);this.J=new L5(this.TM,0,this);g.J(this,this.J);this.D={};this.T=new g.K(this.hB,1E3,this);g.J(this,this.T);this.I=new g.dl(this.NF,1E3,this);g.J(this,this.I);this.N=g.Ha;this.HA();this.Nn();this.Ak()},h9=function(a,b){a.A.Mc(b,
a.i.getVideoData().lengthSeconds)},j9=function(a){h9(a,0);
a.o.stop();i9(a,new g.NB(64))},l9=function(a,b){if(k9(a)&&!a.F){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.fc(c,b));a.g.wA(a.i.getVideoData(1).videoId,c);a.D=r8(a.g).g}},m9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ta;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Me,e5(c));i9(a,new g.NB(1))},n9=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{PQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.F=!1):(a.i.loadModule("captions"),a.F=!0)}else a.i.setOption("captions","track",{})},k9=function(a){return r8(a.g).videoId==a.i.getVideoData(1).videoId},i9=function(a,b){a.B.stop();
var c=a.G;if(!g.TB(c,b)){var d=g.U(b,2);d!=g.U(a.G,2)&&g.RJ(a.i,d);a.G=b;hra(a.A,c,b)}},o9=function(){g.W.call(this,{C:"div",
H:"ytp-mdx-popup-dialog",M:{role:"dialog"},K:[{C:"div",H:"ytp-mdx-popup-dialog-inner-content",K:[{C:"div",H:"ytp-mdx-popup-title",U:"\u0412\u044b \u0432\u044b\u0448\u043b\u0438 \u0438\u0437 \u0430\u043a\u043a\u0430\u0443\u043d\u0442\u0430"},{C:"div",H:"ytp-mdx-popup-description",U:'\u0420\u043e\u043b\u0438\u043a\u0438, \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u0432\u044b \u043f\u043e\u0441\u043c\u043e\u0442\u0440\u0438\u0442\u0435, \u043c\u043e\u0433\u0443\u0442 \u0431\u044b\u0442\u044c \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u044b \u0432 \u0438\u0441\u0442\u043e\u0440\u0438\u044e \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0430 \u043d\u0430 \u0442\u0435\u043b\u0435\u0432\u0438\u0437\u043e\u0440\u0435, \u0447\u0442\u043e \u0441\u043a\u0430\u0436\u0435\u0442\u0441\u044f \u043d\u0430 \u0440\u0435\u043a\u043e\u043c\u0435\u043d\u0434\u0430\u0446\u0438\u044f\u0445. \u0427\u0442\u043e\u0431\u044b \u044d\u0442\u043e\u0433\u043e \u0438\u0437\u0431\u0435\u0436\u0430\u0442\u044c, \u0432\u044b\u0431\u0435\u0440\u0438\u0442\u0435 "\u041e\u0442\u043c\u0435\u043d\u0430" \u0438 \u0432\u043e\u0439\u0434\u0438\u0442\u0435 \u0432 \u0430\u043a\u043a\u0430\u0443\u043d\u0442 \u043d\u0430 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440\u0435.'},
{C:"div",H:"ytp-mdx-privacy-popup-buttons",K:[{C:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],U:"\u041e\u0442\u043c\u0435\u043d\u0430"},{C:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],U:"\u041e\u041a"}]}]}]});this.l=new g.LP(this,250);g.J(this,this.l);this.D=this.i["ytp-mdx-privacy-popup-cancel"];this.L(this.D,"click",this.o);this.A=this.i["ytp-mdx-privacy-popup-confirm"];this.L(this.A,"click",this.B)},p9=function(a){g.W.call(this,{C:"div",
H:"ytp-remote",K:[{C:"div",H:"ytp-remote-display-status",K:[{C:"div",H:"ytp-remote-display-status-icon",K:[g.$O()]},{C:"div",H:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.LP(this,250);g.J(this,this.l);this.o=a;this.L(a,"presentingplayerstatechange",this.A);ira(this,g.NJ(a))},ira=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.ZM('\u041e\u0448\u0438\u0431\u043a\u0430 \u043d\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 "$RECEIVER_NAME"',c):g.UB(b)||g.U(b,4)?g.ZM('\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u043d\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 "$RECEIVER_NAME"',c):g.ZM('\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043e \u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435 \u043a \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0443 "$RECEIVER_NAME"',
c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},q9=function(a,b){g.uT.call(this,"\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u043e \u0434\u043b\u044f \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0430",0,a,b);
this.l=a;this.D={};this.L(a,"onMdxReceiversChange",this.J);this.L(a,"presentingplayerstatechange",this.J);this.J()},r9=function(a){g.rK.call(this,a);
this.i={key:q5(),name:"\u042d\u0442\u043e\u0442 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440"};this.A=null;this.o=[];this.I=this.g=null;this.F=[this.i];this.l=this.i;this.ik=new g.NB(64);this.J=0;this.Qm=-1;this.B=null;if(!g.ly(g.X(this.player))){a=this.player;var b=g.GC(a);b&&(b=b.un())&&(b=new q9(a,b),g.J(this,b));b=new p9(a);g.J(this,b);g.bK(a,b.element,4);this.B=new o9;g.J(this,this.B);g.bK(a,this.B.element,4);this.G=!!S8()}this.D=null},s9=function(a){a.D&&(a.player.removeEventListener("presentingplayerstatechange",
a.D),a.D=null)},hra=function(a,b,c){a.ik=c;
a.player.O("presentingplayerstatechange",new g.XC(c,b))},t9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)Y8();
else{var c;(c=!g.P(g.X(a.player).experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.Po("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.Po("SESSION_INDEX")&&!g.Po("LOGGED_IN")))||a.G||!a.B);c||g.ly(g.X(a.player))||(g.UB(g.NJ(a.player))?a.player.pauseVideo():(a.D=(0,g.y)(a.XL,a),a.player.addEventListener("presentingplayerstatechange",a.D)),a.B&&a.B.l.show(),W8()||(e9=!0));a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(d||e){var f=a.player.getPlaylist();
if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.ua(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Me,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=e5(c))&&(d.locationInfo=c);c=d}else c=null;P8("Connecting to: "+g.rm(b));"cast-selector-receiver"==b.key?(R8(c||null),e8()?Y7().setLaunchParams(c||null):V7("setLaunchParams called before ready.")):!c&&a9()&&O8()==b.key?i5("yt-remote-connection-change",
!0):(Y8(),R8(c||null),c=N8().Qd(),(c=s5(c,b.key))&&Z8(c,1))}},e6={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},d6={"'":"\\'"},jra={},lqa={NN:"atp",cQ:"ska",RP:"que",sP:"mus",bQ:"sus",KO:"dsp",YP:"seq"};
j5.prototype.gg=function(){var a=new j5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var D5,w5="",tqa=F5("loadCastFramework")||F5("loadCastApplicationFramework"),Pqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Sa(L5,g.H);g.h=L5.prototype;g.h.nD=function(a){this.o=arguments;this.g=!1;this.Ca?this.l=(0,g.D)()+this.Xc:this.Ca=g.bl(this.A,this.Xc)};
g.h.stop=function(){this.Ca&&(g.w.clearTimeout(this.Ca),this.Ca=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.B.apply(null,this.o)))};
g.h.V=function(){this.stop();L5.bb.V.call(this)};
g.h.oD=function(){this.l?(this.Ca=g.bl(this.A,this.l-(0,g.D)()),this.l=null):(this.Ca=null,this.i?this.g=!0:(this.g=!1,this.B.apply(null,this.o)))};N5.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
N5.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};O5.prototype.g=null;O5.prototype.getOptions=function(){var a;(a=this.g)||(a={},Q5(this)&&(a[0]=!0,a[1]=!0),a=this.g=a);return a};var u9;g.Sa(P5,O5);u9=new P5;g.h=S5.prototype;g.h.Yg=null;g.h.Ae=!1;g.h.Ti=null;g.h.Bt=null;g.h.Di=null;g.h.Yh=null;g.h.Yf=null;g.h.Cg=null;g.h.qh=null;g.h.sc=null;g.h.fl=0;g.h.Ee=null;g.h.Fo=null;g.h.pg=null;g.h.Nj=-1;g.h.pA=!0;g.h.Ng=!1;g.h.zq=0;g.h.Wn=null;var Z5={},X5={};g.h=S5.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.gM=function(a){a=a.target;var b=this.Wn;b&&3==v6(a)?b.Jj():this.pB(a)};
g.h.pB=function(a){try{if(a==this.sc)a:{var b=v6(this.sc),c=this.sc.A,d=this.sc.getStatus();if(g.Jd&&!g.ld(10)||g.Ld&&!g.kd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.bg&&!z6(this.sc))break a;this.Ng||4!=b||7==c||(8==c||0>=d?this.g.ze(3):this.g.ze(2));i6(this);var e=this.sc.getStatus();this.Nj=e;var f=z6(this.sc);(this.Ae=200==e)?(4==b&&a6(this),this.A?(c6(this,b,f),g.bg&&this.Ae&&3==b&&(this.ca.ea(this.i,"tick",this.aM),this.i.start())):$5(this,f),this.Ae&&!this.Ng&&(4==b?this.g.Kn(this):(this.Ae=
!1,W5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.pg=3,Y5(13)):(this.pg=0,Y5(14)),a6(this),b6(this))}}catch(k){this.sc&&z6(this.sc)}finally{}};
g.h.aM=function(){var a=v6(this.sc),b=z6(this.sc);this.fl<b.length&&(i6(this),c6(this,a,b),this.Ae&&4!=a&&W5(this))};
g.h.wL=function(a){h6((0,g.y)(this.vL,this,a),0)};
g.h.vL=function(a){this.Ng||(i6(this),$5(this,a),W5(this))};
g.h.yz=function(a){h6((0,g.y)(this.uL,this,a),0)};
g.h.uL=function(a){this.Ng||(a6(this),this.Ae=a,this.g.Kn(this),this.g.ze(4))};
g.h.cancel=function(){this.Ng=!0;a6(this)};
g.h.GL=function(){this.Ti=null;var a=(0,g.D)();0<=a-this.Bt?(2!=this.Yh&&this.g.ze(3),a6(this),this.pg=2,Y5(18),b6(this)):g6(this,this.Bt-a)};
g.h.getLastError=function(){return this.pg};g.h=m6.prototype;g.h.xq=null;g.h.Gd=null;g.h.Xn=!1;g.h.xw=null;g.h.gm=null;g.h.er=null;g.h.yq=null;g.h.ge=null;g.h.Cf=-1;g.h.Mj=null;g.h.hj=null;g.h.connect=function(a){this.yq=a;a=n6(this.g,null,this.yq);Y5(3);this.xw=(0,g.D)();var b=this.g.F;null!=b?(this.Mj=b[0],(this.hj=b[1])?(this.ge=1,o6(this)):(this.ge=2,q6(this))):(d5(a,"MODE","init"),this.Gd=new S5(this,void 0,void 0,void 0),this.Gd.Yg=this.xq,V5(this.Gd,a,!1,null,!0),this.ge=0)};
g.h.vC=function(a){if(a)this.ge=2,q6(this);else{Y5(4);var b=this.g;b.Je=b.fg.Cf;T6(b,9)}a&&this.ze(2)};
g.h.Qp=function(a){return this.g.Qp(a)};
g.h.abort=function(){this.Gd&&(this.Gd.cancel(),this.Gd=null);this.Cf=-1};
g.h.ww=function(){return!1};
g.h.rz=function(a,b){this.Cf=a.Nj;if(0==this.ge)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Je=this.Cf;T6(c,2);return}this.Mj=c[0];this.hj=c[1]}else c=this.g,c.Je=this.Cf,T6(c,2);else if(2==this.ge)if(this.Xn)Y5(7),this.er=(0,g.D)();else if("11111"==b){if(Y5(6),this.Xn=!0,this.gm=(0,g.D)(),c=this.gm-this.xw,!g.Jd||g.ld(10)||500>c)this.Cf=200,this.Gd.cancel(),Y5(12),p6(this.g,this,!0)}else Y5(8),this.gm=this.er=(0,g.D)(),this.Xn=!1};
g.h.Kn=function(){this.Cf=this.Gd.Nj;if(this.Gd.Ae)0==this.ge?this.hj?(this.ge=1,o6(this)):(this.ge=2,q6(this)):2==this.ge&&((!g.Jd||g.ld(10)?!this.Xn:200>this.er-this.gm)?(Y5(11),p6(this.g,this,!1)):(Y5(12),p6(this.g,this,!0)));else{0==this.ge?Y5(9):2==this.ge&&Y5(10);var a=this.g;this.Gd.getLastError();a.Je=this.Cf;T6(a,2)}};
g.h.Qk=function(){return this.g.Qk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.ze=function(a){this.g.ze(a)};g.Sa(r6,g.qk);var yqa=/^https?$/i,kra=["POST","PUT"];g.h=r6.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.F+"; newUri="+a);b=b?b.toUpperCase():"GET";this.F=a;this.l="";this.A=0;this.Z=b;this.R=!1;this.i=!0;this.g=this.N?R5(this.N):R5(u9);this.T=this.N?this.N.getOptions():u9.getOptions();this.g.onreadystatechange=(0,g.y)(this.yw,this);try{h5(w6(this,"Opening Xhr")),this.aa=!0,this.g.open(b,String(a),!0),this.aa=!1}catch(f){h5(w6(this,"Error opening Xhr: "+f.message));u6(this,f);return}a=c||"";
var e=this.headers.clone();d&&hqa(d,function(f,k){e.set(k,f)});
d=g.Ya(e.Pd(),xqa);c=g.w.FormData&&a instanceof g.w.FormData;!g.ab(kra,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.X&&(this.g.responseType=this.X);"withCredentials"in this.g&&this.g.withCredentials!==this.S&&(this.g.withCredentials=this.S);try{y6(this),0<this.B&&(this.J=wqa(this.g),h5(w6(this,"Will abort after "+this.B+"ms if incomplete, xhr2 "+this.J)),this.J?(this.g.timeout=this.B,this.g.ontimeout=(0,g.y)(this.zw,this)):this.G=g.bl(this.zw,this.B,this)),h5(w6(this,"Sending request")),this.D=!0,this.g.send(a),this.D=!1}catch(f){h5(w6(this,"Send error: "+f.message)),u6(this,f)}};
g.h.zw=function(){"undefined"!=typeof g.gY&&this.g&&(this.l="Timed out after "+this.B+"ms, aborting",this.A=8,w6(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(w6(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.A=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),t6(this))};
g.h.V=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),t6(this,!0));r6.bb.V.call(this)};
g.h.yw=function(){this.fa()||(this.aa||this.D||this.o?x6(this):this.vK())};
g.h.vK=function(){x6(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<v6(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.u(this.l)?this.l:String(this.l)};g.h=A6.prototype;g.h.vj=null;g.h.Cd=null;g.h.Rb=null;g.h.wq=null;g.h.im=null;g.h.Hu=null;g.h.zm=null;g.h.vk=0;g.h.KH=0;g.h.Uc=null;g.h.ng=null;g.h.qf=null;g.h.Sg=null;g.h.fg=null;g.h.Do=null;g.h.li=-1;g.h.ix=-1;g.h.Je=-1;g.h.Rh=0;g.h.Kh=0;g.h.Og=8;var U6=new g.qk;g.Sa(B6,g.Sj);g.Sa(C6,g.Sj);g.Sa(D6,g.Sj);g.h=A6.prototype;g.h.connect=function(a,b,c,d,e){Y5(0);this.wq=b;this.vj=c||{};d&&g.Da(e)&&(this.vj.OSID=d,this.vj.OAID=e);this.B?(h6((0,g.y)(this.bv,this,a),100),J6(this)):this.bv(a)};
g.h.bv=function(a){this.fg=new m6(this);this.fg.xq=null;this.fg.i=this.A;this.fg.connect(a)};
g.h.ww=function(){return 0==this.g};
g.h.xz=function(a){this.ng=null;O6(this,a)};
g.h.wz=function(){this.qf=null;this.Rb=new S5(this,this.l,"rpc",this.D);this.Rb.Yg=null;this.Rb.zq=0;var a=this.Hu.clone();b5(a,"RID","rpc");b5(a,"SID",this.l);b5(a,"CI",this.Do?"0":"1");b5(a,"AID",this.li);F6(this,a);if(!g.Jd||g.ld(10))b5(a,"TYPE","xmlhttp"),V5(this.Rb,a,!0,this.zm,!1);else{b5(a,"TYPE","html");var b=this.Rb,c=!!this.zm;b.Yh=3;b.Yf=c5(a.clone());f6(b,c)}};
g.h.rz=function(a,b){if(0!=this.g&&(this.Rb==a||this.Cd==a))if(this.Je=a.Nj,this.Cd==a&&3==this.g)if(7<this.Og){try{var c=this.A.parse(b)}catch(f){c=null}if(g.Ka(c)&&3==c.length)if(0==c[0])a:{if(!this.qf){if(this.Rb)if(this.Rb.Di+3E3<this.Cd.Di)K6(this),this.Rb.cancel(),this.Rb=null;else break a;R6(this);Y5(19)}}else this.ix=c[1],0<this.ix-this.li&&37500>c[2]&&this.Do&&0==this.Kh&&!this.Sg&&(this.Sg=h6((0,g.y)(this.mI,this),6E3));else T6(this,11)}else b!=jra.lO.g&&T6(this,11);else if(this.Rb==a&&
K6(this),!g.wb(b)){c=this.A.parse(b);g.Ka(c);for(var d=0;d<c.length;d++){var e=c[d];this.li=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.zm=e[2],e=e[3],null!=e?this.Og=e:this.Og=6,this.g=3,this.Uc&&this.Uc.Vu(),this.Hu=n6(this,this.Qk()?this.zm:null,this.wq),P6(this)):"stop"==e[0]&&T6(this,7):3==this.g&&("stop"==e[0]?T6(this,7):"noop"!=e[0]&&this.Uc&&this.Uc.Uu(e),this.Kh=0)}}};
g.h.mI=function(){null!=this.Sg&&(this.Sg=null,this.Rb.cancel(),this.Rb=null,R6(this),Y5(20))};
g.h.Kn=function(a){if(this.Rb==a){K6(this);this.Rb=null;var b=2}else if(this.Cd==a)this.Cd=null,b=1;else return;this.Je=a.Nj;if(0!=this.g)if(a.Ae)1==b?(b=(0,g.D)()-a.Di,U6.dispatchEvent(new C6(U6,a.qh?a.qh.length:0,b,this.Rh)),I6(this),this.o.length=0):P6(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Je)){if(d=1==b)this.Cd||this.ng||1==this.g||2<=this.Rh?d=!1:(this.ng=h6((0,g.y)(this.xz,this,a),Q6(this,this.Rh)),this.Rh++,d=!0);d=!(d||2==b&&R6(this))}if(d)switch(c){case 1:T6(this,
5);break;case 4:T6(this,10);break;case 3:T6(this,6);break;case 7:T6(this,12);break;default:T6(this,2)}}};
g.h.NC=function(a){if(!g.ab(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.JM=function(a){a?Y5(2):(Y5(1),S6(this,8))};
g.h.Qp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new r6;a.S=!1;return a};
g.h.isActive=function(){return!!this.Uc&&this.Uc.isActive(this)};
g.h.ze=function(a){U6.dispatchEvent(new D6(U6,a))};
g.h.Qk=function(){return!(!g.Jd||g.ld(10))};
g.h=V6.prototype;g.h.Vu=function(){};
g.h.Uu=function(){};
g.h.Tu=function(){};
g.h.Dp=function(){};
g.h.Uv=function(){return{}};
g.h.isActive=function(){return!0};g.h=W6.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.ab(this.g,a)||g.ab(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Vma)(b,a);0<=c?(g.cb(b,c),b=!0):b=!1;return b||g.db(this.i,a)};
g.h.Ec=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};g.Sa(X6,g.H);g.h=X6.prototype;g.h.oL=function(){this.Xc=Math.min(3E5,2*this.Xc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Xc+15E3*Math.random();g.tn(this.g,a);this.i=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Xc=5E3};g.Sa(Y6,V6);g.h=Y6.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Kf=function(a){return this.l.Zg(a)};
g.h.O=function(a,b){return this.l.O.apply(this.l,arguments)};
g.h.dispose=function(){this.ib||(this.ib=!0,g.Bi(this.l),Z6(this),g.Bi(this.i),this.i=null)};
g.h.fa=function(){return this.ib};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.G="";this.i.stop();this.A=a||null;this.o=b||0;a=this.I+"/test";b=this.I+"/bind";var d=new A6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.J),e=this.g;e&&(e.Uc=null);d.Uc=this;this.g=d;e?this.g.connect(a,b,this.B,e.l,e.li):c?this.g.connect(a,b,this.B,c.sessionId,c.arrayId):this.g.connect(a,b,this.B)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):$6(this)&&L6(this.g,c)};
g.h.Vu=function(){this.i.reset();this.A=null;this.o=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)L6(this.g,a[b])}this.O("handlerOpened")};
g.h.Tu=function(a){var b=2==a&&401==this.g.Je;4==a||b||this.i.start();this.O("handlerError",a)};
g.h.Dp=function(a){if(!this.i.isActive())this.O("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Uv=function(){var a={v:2};this.G&&(a.gsessionid=this.G);0!=this.o&&(a.ui=""+this.o);0!=this.F&&(a.ui=""+this.F);this.A&&g.fc(a,this.A);return a};
g.h.Uu=function(a){"S"==a[0]?this.G=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),H6(this.g)):this.O("handlerMessage",new Aqa(a[0],a[1]))};
g.h.qM=function(){this.i.isActive();var a=this.g,b=0;a.Rb&&b++;a.Cd&&b++;0==b&&this.connect(this.A,this.o)};a7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
a7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
a7.prototype.A=function(a){a(Error("request timed out"))};var Gqa=(0,g.D)(),f7=null,j7=Array(50),i7=-1,k7=!1;g.Sa(l7,g.O);l7.prototype.Qd=function(){return this.g};
l7.prototype.contains=function(a){return!!r5(this.g,a)};
l7.prototype.get=function(a){return a?s5(this.g,a):null};
l7.prototype.info=function(a){h7(this.D,a)};g.t(n7,g.O);g.h=n7.prototype;g.h.start=function(){!this.g&&isNaN(this.Ca)&&this.sB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.Ca)||(g.Zo(this.Ca),this.Ca=NaN)};
g.h.V=function(){this.stop();g.O.prototype.V.call(this)};
g.h.sB=function(){this.Ca=NaN;this.g=g.Up(b7(this.B,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:this.A},timeout:5E3,onSuccess:(0,g.y)(this.mN,this),onError:(0,g.y)(this.lN,this),oe:(0,g.y)(this.nN,this)})};
g.h.mN=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.O("pairingComplete",new k5(c))};
g.h.lN=function(a){this.g=null;a.status&&404==a.status?this.i>=lra.length?this.O("pairingFailed",Error("DIAL polling timed out")):(a=lra[this.i],this.Ca=g.Xo((0,g.y)(this.sB,this),a),this.i++):this.O("pairingFailed",Error("Server error "+a.status))};
g.h.nN=function(){this.g=null;this.O("pairingFailed",Error("Server not responding"))};
var lra=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(p7,l7);g.h=p7.prototype;g.h.start=function(){o7(this)&&this.O("screenChange");!g.Cs("yt-remote-lounge-token-expiration")&&q7(this);g.Zo(this.i);this.i=g.Xo((0,g.y)(this.start,this),1E4)};
g.h.add=function(a,b){o7(this);m7(this,a);r7(this,!1);this.O("screenChange");b(a);a.token||q7(this)};
g.h.remove=function(a,b){var c=o7(this);Iqa(this,a)&&(r7(this,!1),c=!0);b(a);c&&this.O("screenChange")};
g.h.zo=function(a,b,c,d){var e=o7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,r7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.O("screenChange")};
g.h.V=function(){g.Zo(this.i);p7.bb.V.call(this)};
g.h.yD=function(a){o7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}r7(this,!b);b&&h7(this.D,"Missed "+b+" lounge tokens.")};
g.h.xD=function(a){h7(this.D,"Requesting lounge tokens failed: "+a)};g.t(t7,g.O);g.h=t7.prototype;g.h.start=function(){var a=parseInt(g.Cs("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.D)()-144E5<a?0:a)?w7(this):(this.o=(0,g.D)()+3E5,g.Bs("yt-remote-fast-check-period",this.o),this.Fs())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){s7("Updating availability on schedule.");var a=this.B(),b=g.Lb(this.g,function(c,d){return c&&!!s5(a,d)},this);
v7(this,b)};
g.h.V=function(){g.Zo(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.O.prototype.V.call(this)};
g.h.Fs=function(){g.Zo(this.l);this.l=NaN;this.i&&this.i.abort();var a=x7(this);if(f5(a)){var b=b7(this.A,"/pairing/get_screen_availability");this.i=c7(this.A,b,{lounge_token:g.Rb(a).join(",")},(0,g.y)(this.RK,this,a),(0,g.y)(this.QK,this))}else v7(this,{}),w7(this)};
g.h.RK=function(a,b){this.i=null;var c=g.Rb(x7(this));if(g.rb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;v7(this,d);w7(this)}else this.Ib("Changing Screen set during request."),this.Fs()};
g.h.QK=function(a){this.Ib("Screen availability failed: "+a);this.i=null;w7(this)};
g.h.Ib=function(a){h7("OnlineScreenService",a)};g.Sa(y7,l7);g.h=y7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.O("screenChange"),this.i.isEmpty()||this.O("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.zo=function(a,b,c,d){this.l.contains(a)?this.l.zo(a,b,c,d):(a="Updating name of unknown screen: "+a.name,h7(this.D,a),d(Error(a)))};
g.h.Qd=function(a){return a?this.g:g.fb(this.g,(0,g.Vd)(this.o,function(b){return!this.contains(b)},this))};
g.h.tB=function(){return(0,g.Vd)(this.Qd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.uB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new n7(this.B,a,b,c);f.subscribe("pairingComplete",(0,g.y)(function(k){g.Bi(f);d(z7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.Bi(f);e(k)});
f.start();return(0,g.y)(f.stop,f)};
g.h.pN=function(a,b,c,d){g.Up(b7(this.B,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:a},timeout:5E3,onSuccess:(0,g.y)(function(e,f){var k=new k5(f.screen||{});if(!k.name||B7(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);B7(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(z7(this,k))},this),
onError:(0,g.y)(function(e){d(Error("pairing request failed: "+e.status))},this),
oe:(0,g.y)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.Bi(this.l);g.Bi(this.i);y7.bb.V.call(this)};
g.h.GD=function(){C7(this);this.O("screenChange");this.i.update()};
y7.prototype.dispose=y7.prototype.dispose;g.Sa(E7,g.O);g.h=E7.prototype;g.h.Mn=function(a){this.l=a;this.O("sessionScreen",this.l)};
g.h.Td=function(a){this.fa()||(a&&F7(this,""+a),this.l=null,this.O("sessionScreen",null))};
g.h.info=function(a){h7(this.T,a)};
g.h.wB=function(){return null};
g.h.Os=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.y)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.y)(function(){F7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.Os("");E7.bb.V.call(this)};g.Sa(H7,E7);g.h=H7.prototype;g.h.Ns=function(a){if(this.g){if(this.g==a)return;F7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.B);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.A)}this.g=a;this.g.addUpdateListener(this.B);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.A);Mqa(this)};
g.h.mi=function(a){this.info("launchWithParams no-op for Cast: "+g.rm(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.y)(function(){this.Td()},this),(0,g.y)(function(){this.Td(Error("Failed to stop receiver app."))},this)):this.Td(Error("Stopping cast device witout session."))};
g.h.Os=g.Ha;g.h.V=function(){this.info("disposeInternal");g.Zo(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.B),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.A));this.g=null;H7.bb.V.call(this)};
g.h.RL=function(a,b){if(!this.fa())if(b){var c=M5(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.rm(c));switch(d){case "mdxSessionStatus":G7(this,c.screenId);break;default:F7(this,"Unknown youtube message: "+d)}}else F7(this,"Unable to parse message.")}else F7(this,"No data in message.")};
g.h.mw=function(a,b,c,d){A7(this.G,this.i.label,a,this.i.friendlyName,(0,g.y)(function(e){e?b(e):0<=d?(F7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Xo((0,g.y)(this.mw,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.wB=function(){return this.g};
g.h.qN=function(a){this.fa()||a||(F7(this,"Cast session died."),this.Td())};g.Sa(I7,E7);g.h=I7.prototype;g.h.Ns=function(a){this.o=a;this.o.addUpdateListener(this.J)};
g.h.mi=function(a){this.A=a;this.D()};
g.h.stop=function(){this.g();this.g=g.Ha;g.Zo(this.B);this.o?this.o.stop((0,g.y)(this.Td,this,null),(0,g.y)(this.Td,this,"Failed to stop DIAL device.")):this.Td()};
g.h.V=function(){this.g();this.g=g.Ha;g.Zo(this.B);this.o&&this.o.removeUpdateListener(this.J);this.o=null;I7.bb.V.call(this)};
g.h.tN=function(a){this.fa()||a||(F7(this,"DIAL session died."),this.g(),this.g=g.Ha,this.Td())};
g.h.Lq=function(a){this.I=q5();if(this.A){var b=new chrome.cast.DialLaunchResponse(!0,K7(this));a(b);J7(this)}else this.D=(0,g.y)(function(){g.Zo(this.B);this.D=g.Ha;this.B=NaN;var c=new chrome.cast.DialLaunchResponse(!0,K7(this));a(c);J7(this)},this),this.B=g.Xo((0,g.y)(function(){this.D()},this),100)};
g.h.bE=function(a,b,c){A7(this.G,this.F.receiver.label,a,this.i.friendlyName,(0,g.y)(function(d){d&&d.token?(this.Mn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Lq(b,c)},this),(0,g.y)(function(d){F7(this,"Failed to get DIAL screen: "+d);
this.Lq(b,c)},this))};g.Sa(L7,E7);L7.prototype.stop=function(){this.Td()};
L7.prototype.Ns=g.Ha;L7.prototype.mi=function(){g.Zo(this.g);this.g=NaN;var a=s5(this.G.Qd(),this.i.label);a?this.Mn(a):this.Td(Error("No such screen"))};
L7.prototype.V=function(){g.Zo(this.g);this.g=NaN;L7.bb.V.call(this)};g.Sa(M7,g.O);g.h=M7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.y)(this.AK,this);c=new chrome.cast.ApiConfig(c,(0,g.y)(this.uz,this),f,d,e);c.customDialLaunchCallback=(0,g.y)(this.NI,this);chrome.cast.initialize(c,(0,g.y)(function(){this.fa()||
(chrome.cast.addReceiverActionListener(this.o),Dqa(),this.i.subscribe("onlineScreenChange",(0,g.y)(this.vB,this)),this.l=R7(this),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.y)(function(k){this.Ib("Failed to set initial custom receivers: "+g.rm(k))},this)),this.O("yt-remote-cast2-availability-change",P7(this)),b(!0))},this),(0,g.y)(function(k){this.Ib("Failed to initialize API: "+g.rm(k));
b(!1)},this))};
g.h.xM=function(a,b){O7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)O7("Unsetting old screen status: "+this.g.i.friendlyName),Q7(this,null)}if(a&&b){if(!this.g){c=s5(this.i.Qd(),a);if(!c){O7("setConnectedScreenStatus: Unknown screen.");return}var d=N7(this,c);d||(O7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ha,(0,g.y)(function(e){this.Ib("Failed to set initial custom receivers: "+g.rm(e))},this)));
O7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);Q7(this,new L7(this.i,d),!0)}this.g.Os(b)}else O7("setConnectedScreenStatus: no screen.")};
g.h.yM=function(a){this.fa()?this.Ib("Setting connection data on disposed cast v2"):this.g?this.g.mi(a):this.Ib("Setting connection data without a session")};
g.h.sN=function(){this.fa()?this.Ib("Stopping session on disposed cast v2"):this.g?(this.g.stop(),Q7(this,null)):O7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.y)(this.uz,this),(0,g.y)(this.XK,this))};
g.h.V=function(){this.i.unsubscribe("onlineScreenChange",(0,g.y)(this.vB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.db(g.x("yt.mdx.remote.debug.handlers_")||[],d7);g.Bi(this.g);M7.bb.V.call(this)};
g.h.Ib=function(a){h7("Controller",a)};
g.h.vz=function(a,b){this.g==a&&(b||Q7(this,null),this.O("yt-remote-cast2-session-change",b))};
g.h.wK=function(a,b){if(!this.fa())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),O7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)O7("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{O7("onReceiverAction_: Casting to active receiver.");this.g.l&&this.O("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:Q7(this,
new L7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:Q7(this,new I7(this.i,a,this.B));break;case chrome.cast.ReceiverType.CAST:Q7(this,new H7(this.i,a));break;default:this.Ib("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Ib("Stopping receiver w/o session: "+a.friendlyName)}else this.Ib("onReceiverAction_ called without receiver.")};
g.h.NI=function(a){if(this.fa())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Ib("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Ib("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return O7("Reselecting dial screen."),
this.O("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Ib('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);Q7(this,new I7(this.i,b,this.B))}b=this.g;b.F=a;return b.F.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.y)(b.bE,b,(b.F.extraData||{}).screenId||null)):new Promise((0,g.y)(b.Lq,b))};
g.h.uz=function(a){if(!this.fa()){O7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)O7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),Q7(this,new H7(this.i,b),!0);else{this.Ib("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=s5(this.i.Qd(),c.label);d&&l5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(O7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Bi(this.g),this.g=new H7(this.i,b),this.g.subscribe("sessionScreen",(0,g.y)(this.vz,this,this.g)),this.g.mi(null));this.g.Ns(a)}}};
g.h.rN=function(){return this.g?this.g.wB():null};
g.h.XK=function(a){this.fa()||(this.Ib("Failed to estabilish a session: "+g.rm(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&Q7(this,null))};
g.h.AK=function(a){O7("Receiver availability updated: "+a);if(!this.fa()){var b=P7(this);this.A=a==chrome.cast.ReceiverAvailability.AVAILABLE;P7(this)!=b&&this.O("yt-remote-cast2-availability-change",P7(this))}};
g.h.vB=function(){this.fa()||(this.l=R7(this),O7("Updating custom receivers: "+g.rm(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.y)(function(){this.Ib("Failed to set custom receivers.")},this)),this.O("yt-remote-cast2-availability-change",P7(this)))};
M7.prototype.setLaunchParams=M7.prototype.yM;M7.prototype.setConnectedScreenStatus=M7.prototype.xM;M7.prototype.stopSession=M7.prototype.sN;M7.prototype.getCastSession=M7.prototype.rN;M7.prototype.requestSession=M7.prototype.requestSession;M7.prototype.init=M7.prototype.init;M7.prototype.dispose=M7.prototype.dispose;var $7=[];h8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";i8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Ke=a.hasPrevious,this.hasNext=a.hasNext,this.D=a.playerTime,this.B=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.F=a.duration,this.G=a.loadedTime,this.l=a.liveIngestionTime,this.A=
!isNaN(this.l))};
h8.prototype.isAdPlaying=function(){return 1081==this.playerState};
h8.prototype.getDuration=function(){return this.A?this.F+j8(this):this.F};
h8.prototype.clone=function(){return new h8(n8(this))};g.t(q8,g.O);g.h=q8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ha,y8(this,"play")):w8(this,"play"),v8(this,1,l8(r8(this))),this.O("remotePlayerChange")):t8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ha,y8(this,"pause")):w8(this,"pause"),v8(this,2,l8(r8(this))),this.O("remotePlayerChange")):t8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=r8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ha,y8(this,"seekTo",{newTime:a}))}else w8(this,"seekTo",{newTime:a});v8(this,3,a);this.O("remotePlayerChange")}else t8(this,g.Qa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ha,y8(this,"stopVideo")):w8(this,"stopVideo");var a=r8(this);a.index=-1;a.videoId="";i8(a);u8(this,a);this.O("remotePlayerChange")}else t8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=r8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.y)(function(){h7("CP","set receiver volume: "+d)},this),(0,g.y)(function(){this.Ib("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.y)(function(){h7("CP","set receiver muted: "+b)},this),(0,g.y)(function(){this.Ib("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);w8(this,"setVolume",e)}c.muted=b;c.volume=a;u8(this,c)}else t8(this,g.Qa(this.setVolume,a,b))};
g.h.wA=function(a,b){if(1==this.g){var c=r8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.rm(b.style),g.fc(d,c.g));w8(this,"setSubtitlesTrack",d);u8(this,c)}else t8(this,g.Qa(this.wA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();w8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=r8(this);d.audioTrackId=c;u8(this,d)}else t8(this,g.Qa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=r8(this);c=c||0;var m={videoId:a,currentIndex:c};m8(l,a,c);g.Da(b)&&(k8(l,b),m.currentTime=b);g.Da(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.rm(k));w8(this,"setPlaylist",m);d||u8(this,l)};
g.h.Rn=function(a,b){if(1==this.g){if(a&&b){var c=r8(this);m8(c,a,b);u8(this,c)}w8(this,"previous")}else t8(this,g.Qa(this.Rn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=r8(this);m8(c,a,b);u8(this,c)}w8(this,"next")}else t8(this,g.Qa(this.nextVideo,a,b))};
g.h.zv=function(){1==this.g?w8(this,"dismissAutoplay"):t8(this,this.zv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.O("proxyStateChange",a,this.g)}g.O.prototype.dispose.call(this)};
g.h.V=function(){s8(this);this.o=null;this.A.clear();p8(this,null);g.O.prototype.V.call(this)};
g.h.Et=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.O("proxyStateChange",b,a);if(1==a)for(;!this.A.isEmpty();)b=a=this.A,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.tK=function(a,b){this.O(a,b)};
g.h.sI=function(a){if(!a)this.yk(null),p8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=r8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)h7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,u8(this,b)}};
g.h.yk=function(a){h7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.F);if(this.i=a)this.i.addUpdateListener(this.F),x8(this),this.O("remotePlayerChange")};
g.h.rI=function(a){a?(x8(this),this.O("remotePlayerChange")):this.yk(null)};
g.h.jt=function(){w8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.GI=function(){var a=d8();a&&p8(this,a)};
g.h.Ib=function(a){h7("CP",a)};g.t(z8,g.O);g.h=z8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Da(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Da(k)&&(l.currentIndex=k);c&&(this.Oa.listId=c);this.Oa.videoId=d;this.Oa.index=k||0;this.Oa.state=3;k8(this.Oa,m);this.o="UNSUPPORTED";A8("Connecting with setPlaylist and params: "+g.rm(l));this.g.connect({method:"setPlaylist",
params:g.rm(l)},a,z5())}else A8("Connecting without params"),this.g.connect({},a,z5());Tqa(this)};
g.h.dispose=function(){this.fa()||(this.O("beforeDispose"),B8(this,3));g.O.prototype.dispose.call(this)};
g.h.V=function(){C8(this);E8(this);D8(this);g.Zo(this.D);this.D=NaN;g.Zo(this.F);this.F=NaN;this.l=null;g.dr(this.T);this.T.length=0;this.g.dispose();g.O.prototype.V.call(this);this.o=this.B=this.i=this.Oa=this.g=null};
g.h.rD=function(){this.Oh(2)};
g.h.wI=function(){A8("Channel opened");this.J&&(this.J=!1,D8(this),this.I=g.Xo((0,g.y)(function(){A8("Timing out waiting for a screen.");this.Oh(1)},this),15E3));
rqa(Bqa(this.g),this.N)};
g.h.tI=function(){A8("Channel closed");isNaN(this.A)?C5(!0):C5();this.dispose()};
g.h.uI=function(a){C5();isNaN(this.Dj())?(A8("Channel error: "+a+" without reconnection"),this.dispose()):(this.J=!0,A8("Channel error: "+a+" with reconnection in "+this.Dj()+" ms"),B8(this,2))};
g.h.vI=function(a){a.params?A8("Received: action="+a.action+", params="+g.rm(a.params)):A8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=M5(a.params.devices);this.i=(0,g.B)(a,function(c){return new j5(c)});
a=!!g.Ya(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
H8(this,a);break;case "loungeScreenDisconnected":g.eb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
H8(this,!1);break;case "remoteConnected":var b=new j5(M5(a.params.device));g.Ya(this.i,function(c){return b?c.id==b.id:!1})||eqa(this.i,b);
break;case "remoteDisconnected":b=new j5(M5(a.params.device));g.eb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":I8(this,a);break;case "nowPlaying":Wqa(this,a);break;case "onStateChange":J8(this,a);break;case "onAdStateChange":Xqa(this,a);break;case "onVolumeChanged":Yqa(this,a);break;case "onSubtitlesTrackChanged":Vqa(this,a);break;case "nowAutoplaying":Zqa(this,a);break;case "autoplayDismissed":this.O("autoplayDismissed");break;case "autoplayUpNext":this.B=a.params.videoId||null;this.O("autoplayUpNext",this.B);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.O("autoplayModeChange",this.o);"DISABLED"==this.o&&this.O("autoplayDismissed");break;case "onHasPreviousNextChanged":$qa(this,a);break;case "requestAssistedSignIn":this.O("assistedSignInRequested",a.params.authCode);break;default:A8("Unrecognized action: "+a.action)}};
g.h.nM=function(){if(this.l){var a=this.l;this.l=null;this.Oa.videoId!=a&&F8(this,"getNowPlaying")}};
g.h.hD=function(){var a=3;this.fa()||(a=0,isNaN(this.Dj())?$6(this.g)&&isNaN(this.A)&&(a=1):a=2);return a};
g.h.Oh=function(a){A8("Disconnecting with "+a);C8(this);this.O("beforeDisconnect",a);1==a&&C5();Z6(this.g,a);this.dispose()};
g.h.gD=function(){var a=this.Oa;this.l&&(a=this.Oa.clone(),m8(a,this.l,a.index));return n8(a)};
g.h.zM=function(a){var b=new h8(a);b.videoId&&b.videoId!=this.Oa.videoId&&(this.l=b.videoId,g.Zo(this.D),this.D=g.Xo((0,g.y)(this.nM,this),5E3));var c=[];this.Oa.listId==b.listId&&this.Oa.videoId==b.videoId&&this.Oa.index==b.index||c.push("remoteQueueChange");this.Oa.playerState==b.playerState&&this.Oa.volume==b.volume&&this.Oa.muted==b.muted&&l8(this.Oa)==l8(b)&&g.rm(this.Oa.g)==g.rm(b.g)||c.push("remotePlayerChange");this.Oa.reset(a);(0,g.z)(c,function(d){this.O(d)},this)};
g.h.kw=function(){var a=this.g.B.id,b=g.Ya(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Dj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.D)():NaN};
g.h.aD=function(){return this.o||"UNSUPPORTED"};
g.h.bD=function(){return this.B||""};
g.h.kN=function(){if(!isNaN(this.Dj())){var a=this.g.i;g.un(a.g);a.start()}};
g.h.uM=function(a,b){F8(this,a,b);G8(this)};
z8.prototype.subscribe=z8.prototype.subscribe;z8.prototype.unsubscribeByKey=z8.prototype.Kf;z8.prototype.getProxyState=z8.prototype.hD;z8.prototype.disconnect=z8.prototype.Oh;z8.prototype.getPlayerContextData=z8.prototype.gD;z8.prototype.setPlayerContextData=z8.prototype.zM;z8.prototype.getOtherConnectedRemoteId=z8.prototype.kw;z8.prototype.getReconnectTimeout=z8.prototype.Dj;z8.prototype.getAutoplayMode=z8.prototype.aD;z8.prototype.getAutoplayVideoId=z8.prototype.bD;z8.prototype.reconnect=z8.prototype.kN;
z8.prototype.sendMessage=z8.prototype.uM;g.t(K8,l7);g.h=K8.prototype;g.h.Qd=function(a){return this.Wc.$_gs(a)};
g.h.contains=function(a){return!!this.Wc.$_c(a)};
g.h.get=function(a){return this.Wc.$_g(a)};
g.h.start=function(){this.Wc.$_st()};
g.h.add=function(a,b,c){this.Wc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Wc.$_r(a,b,c)};
g.h.zo=function(a,b,c,d){this.Wc.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.i.length;a<b;++a)this.Wc.$_ubk(this.i[a]);this.i.length=0;this.Wc=null;l7.prototype.V.call(this)};
g.h.oN=function(){this.O("screenChange")};
g.h.YJ=function(){this.O("onlineScreenChange")};
y7.prototype.$_st=y7.prototype.start;y7.prototype.$_gspc=y7.prototype.pN;y7.prototype.$_gsppc=y7.prototype.uB;y7.prototype.$_c=y7.prototype.contains;y7.prototype.$_g=y7.prototype.get;y7.prototype.$_a=y7.prototype.add;y7.prototype.$_un=y7.prototype.zo;y7.prototype.$_r=y7.prototype.remove;y7.prototype.$_gs=y7.prototype.Qd;y7.prototype.$_gos=y7.prototype.tB;y7.prototype.$_s=y7.prototype.subscribe;y7.prototype.$_ubk=y7.prototype.Kf;var f9=null,e9=!1,L8=null,M8=null,b9=null,Q8=[];g.t(g9,g.H);g.h=g9.prototype;
g.h.V=function(){g.H.prototype.V.call(this);this.o.stop();this.B.stop();this.J.stop();this.N();this.g.unsubscribe("proxyStateChange",this.qz,this);this.g.unsubscribe("remotePlayerChange",this.Ak,this);this.g.unsubscribe("remoteQueueChange",this.Nn,this);this.g.unsubscribe("autoplayUpNext",this.Ty,this);this.g.unsubscribe("previousNextChange",this.nz,this);this.g.unsubscribe("nowAutoplaying",this.jz,this);this.g.unsubscribe("autoplayDismissed",this.Sy,this);this.g=this.A=null};
g.h.Ox=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(k9(this)){if(!r8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==r8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.Jj(c[0],c[1]);break;case "control_subtitles_set_track":l9(this,c[0]);break;case "control_set_audio_track":c=c[0],k9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();m9(this,0==c?void 0:c);break;case "control_seek":m9(this,c[0]);break;case "control_subtitles_set_track":l9(this,c[0]);break;case "control_set_audio_track":c=c[0],k9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.qI=function(a){this.J.nD(a)};
g.h.TM=function(a){this.Ox("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.HA=function(){var a=this.i.getOption("captions","track");g.Yb(a)||l9(this,a)};
g.h.ez=function(a){if(k9(this)){this.g.unsubscribe("remotePlayerChange",this.Ak,this);var b=Math.round(a.volume);a=!!a.muted;var c=r8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.T.start();this.g.subscribe("remotePlayerChange",this.Ak,this)}};
g.h.tJ=function(){g.Yb(this.D)||n9(this,this.D);this.F=!1};
g.h.qz=function(a,b){this.B.stop();2==b&&this.GA()};
g.h.Ak=function(){if(k9(this)){this.o.stop();var a=r8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.A.Qm=1;break;case 1082:case 1083:this.A.Qm=0;break;default:this.A.Qm=-1}switch(a.playerState){case 1081:case 1:i9(this,new g.NB(8));this.FA();break;case 1085:case 3:i9(this,new g.NB(9));break;case 1083:case 0:i9(this,new g.NB(2));this.I.stop();h9(this,this.i.getVideoData().lengthSeconds);break;case 1084:i9(this,new g.NB(4));break;case 2:i9(this,new g.NB(4));h9(this,l8(a));
break;case -1:i9(this,new g.NB(64));break;case -1E3:i9(this,new g.NB(128,{errorCode:"mdx.remoteerror",errorMessage:"\u0412\u0438\u0434\u0435\u043e \u043d\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u043d\u043e \u0434\u043b\u044f \u0443\u0434\u0430\u043b\u0435\u043d\u043d\u043e\u0433\u043e \u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u044f."}))}a=r8(this.g).g;var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&
a.kind==b.kind:1)||(this.D=a,n9(this,a));a=r8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.T.isActive()||this.hB()}else j9(this)};
g.h.nz=function(){this.i.O("mdxpreviousnextchange")};
g.h.Nn=function(){k9(this)||j9(this)};
g.h.uC=function(){this.g.zv()};
g.h.Ty=function(a){a&&(a=g.Up("/watch_queue_ajax",{method:"GET",td:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.y)(this.zL,this)}))&&(this.N=(0,g.y)(a.abort,a))};
g.h.zL=function(a,b){var c=new g.wA(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.O("mdxautoplayupnext",c)};
g.h.jz=function(a){isNaN(a)||this.i.O("mdxnowautoplaying",a)};
g.h.Sy=function(){this.i.O("mdxautoplaycanceled")};
g.h.NF=function(a,b){-1==r8(this.g).playerState?m9(this,a):b&&this.g.seekTo(a)};
g.h.hB=function(){if(k9(this)){var a=r8(this.g);this.l.Qa(this.R);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.R=this.l.L(this.i,"onVolumeChange",this.ez)}};
g.h.FA=function(){this.o.stop();if(!this.g.fa()){var a=r8(this.g);1==a.playerState&&i9(this,new g.NB(8));h9(this,l8(a));this.o.start()}};
g.h.GA=function(){this.B.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.B.start()};g.t(o9,g.W);o9.prototype.o=function(){i5("mdx-privacy-popup-cancel");this.l.hide()};
o9.prototype.B=function(){i5("mdx-privacy-popup-confirm");this.l.hide()};g.t(p9,g.W);p9.prototype.A=function(a){ira(this,a.state)};g.t(q9,g.uT);q9.prototype.J=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.D=g.tb(a,this.B,this),g.wT(this,(0,g.B)(a,this.B)),a=this.l.getOption("remote","currentReceiver"),this.me(this.B(a)),this.enable(!0)):this.enable(!1)};
q9.prototype.B=function(a){return a.key};
q9.prototype.ye=function(a){return"cast-selector-receiver"==a?"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c":this.D[a].name};
q9.prototype.Kc=function(a){g.uT.prototype.Kc.call(this,a);this.l.setOption("remote","currentReceiver",this.D[a]);this.o.kb()};g.t(r9,g.rK);g.h=r9.prototype;
g.h.create=function(){era(g.cy(g.X(this.player)));this.o.push(g.dp("yt-remote-before-disconnect",this.nI,this));this.o.push(g.dp("yt-remote-connection-change",this.BK,this));this.o.push(g.dp("yt-remote-receiver-availability-change",this.oz,this));this.o.push(g.dp("yt-remote-auto-connect",this.zK,this));this.o.push(g.dp("yt-remote-receiver-resumed",this.yK,this));this.o.push(g.dp("mdx-privacy-popup-confirm",this.dM,this));this.o.push(g.dp("mdx-privacy-popup-cancel",this.cM,this));this.oz()};
g.h.load=function(){this.player.cancelPlayback();g.rK.prototype.load.call(this);this.A=new g9(this,this.player,this.g);var a=(a=d9())?a.currentTime:0;var b=a9()?new q8(W8(),void 0):null;0==a&&b&&(a=l8(r8(b)));0!=a&&this.Mc(a);hra(this,this.ik,this.ik);g.yX(this.player.app,6)};
g.h.unload=function(){this.player.O("mdxautoplaycanceled");this.l=this.i;g.Ci(this.A,this.g);this.g=this.A=null;g.rK.prototype.unload.call(this);g.yX(this.player.app,5);s9(this)};
g.h.V=function(){g.ep(this.o);g.rK.prototype.V.call(this)};
g.h.Ye=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.A.Ox.apply(this.A,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.Qm};
g.h.jD=function(){return this.loaded?this.A.suggestion:null};
g.h.Ke=function(){return this.g?r8(this.g).Ke:!1};
g.h.hasNext=function(){return this.g?r8(this.g).hasNext:!1};
g.h.Mc=function(a,b){this.J=a||0;this.player.O("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.J};
g.h.getProgressState=function(){var a=r8(this.g),b=this.player.getVideoData();return{allowSeeking:g.P(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.dc():!a.isAdPlaying()&&this.player.dc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.l+j8(a):a.l,isAtLiveHead:1>=(a.A?a.i+j8(a):a.i)-this.getCurrentTime(),loaded:a.G,seekableEnd:a.A?a.i+j8(a):a.i,seekableStart:0<a.o?a.o+
j8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.Rn=function(){this.g&&this.g.Rn()};
g.h.nI=function(a){1==a&&(this.I=this.g?r8(this.g):null)};
g.h.BK=function(){var a=a9()?new q8(W8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.I=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.Bi(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,l8(a)));this.player.O("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.oz=function(){this.F=[this.i].concat(fra());var a=X8()||this.i;t9(this,a);this.player.ma("onMdxReceiversChange")};
g.h.XL=function(a){!this.G&&g.ZC(a,8)&&(this.player.pauseVideo(),s9(this))};
g.h.zK=function(){var a=X8();t9(this,a)};
g.h.yK=function(){this.l=X8()};
g.h.dM=function(){this.G=!0;s9(this);e9=!1;f9&&Z8(f9,1);f9=null};
g.h.cM=function(){this.G=!1;s9(this);t9(this,this.i);this.l=this.i;e9=!1;f9=null;this.player.playVideo()};
g.h.wc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?f8():t9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&f8(),!0):!1}};
g.h.jt=function(){this.g.jt()};
g.h.Cb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.NU.remote=r9;})(_yt_player);
