links = [
  ('https://korvet-m.com.ua/index.php?route=product/category&path=74&limit=100'         ,'9001','Запчасти для транспорта'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=74_76&limit=100'      ,'9002','Автозапчасти и аксессуары'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=74_76_77&limit=100'   ,'9003','Аксессуары для авто'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=74_75&limit=100'      ,'9004','Прочие запчасти'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=85&limit=100'         ,'9005','Красота и здоровье'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=82&limit=100'         ,'9006','Рации'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=71&limit=100'         ,'9007','Строительство/ремонт'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=71_73&limit=100'      ,'9008','Прочие стройматериалы'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=71_72&limit=100'      ,'9009','Сантехника'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=90&limit=100'         ,'9010','Хобби отдых и спорт'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=90_86&limit=100'      ,'9011','Велосипеды'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=61&limit=100'         ,'9012','Дом и сад'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=61_78&limit=100'      ,'9013','Предметы интерьера '),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=61_78_79&limit=100'   ,'9014','Светильники'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=61_68&limit=100'      ,'9015','Сад/огород'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=61_83&limit=100'      ,'9016','Товары для кухни'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=61_83_84&limit=100'   ,'9017','Посуда'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=61_83_84_88&limit=100','9018','Скороводки'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=61_83_81&limit=100'   ,'9019','Техника для кухни'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=61_67&limit=100'      ,'9020','Хозяйственный инвентарь/ бытовая химия'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=61_60_66&limit=100'   ,'9021','Пневмоинструмент'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=61_60_64&limit=100'   ,'9022','Прочий инструмент'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=61_60_62&limit=100'   ,'9023','Электроинструмент'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=61_60_62_80&limit=100','9024','Удлиннители'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=61_60_62_89&limit=100','9025','Комплектующие для инструмента'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=61_60_63&limit=100'   ,'9026','Ручной инструмент'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=61_60_63_87&limit=100','9027','Набор инструментов'),
  ('https://korvet-m.com.ua/index.php?route=product/category&path=61_60_65&limit=100'   ,'9028','Бензоинструмент'),
]

